
const ENEMY_TYPE_DRAGON     = "Dragon"
const ENEMY_TYPE_GOLEM      = "Golem"
const ENEMY_TYPE_ASSASSIN   = "Assassin"
const ENEMY_TYPE_GRIFFIN    = "Griffon"
const ENEMY_TYPE_BERSERKER  = "Berserker"
const ENEMY_TYPE_WEREWOLF   = "Loup Garou"

const ENEMY_TYPE_LIST = [ENEMY_TYPE_DRAGON, ENEMY_TYPE_GOLEM, ENEMY_TYPE_ASSASSIN, ENEMY_TYPE_GRIFFIN, ENEMY_TYPE_BERSERKER, ENEMY_TYPE_WEREWOLF]